// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnePieceTcg.DAL.Data;

#nullable disable

namespace OnePieceTcg.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250706201710_InitialCreate1")]
    partial class InitialCreate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnePieceTcg.Domain.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardSetId")
                        .HasColumnType("int");

                    b.Property<int?>("CardTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RarityId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialRarityId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CardSetId");

                    b.HasIndex("CardTypeId");

                    b.HasIndex("ColorId");

                    b.HasIndex("RarityId");

                    b.HasIndex("SpecialRarityId");

                    b.HasIndex("UserId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.CardLine", b =>
                {
                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("LineId")
                        .HasColumnType("int");

                    b.HasKey("CardId", "LineId");

                    b.HasIndex("LineId");

                    b.ToTable("CardTraits");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.CardSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CardSets");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.CardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CardTypes");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.CollectionCard", b =>
                {
                    b.Property<int>("CollectionId")
                        .HasColumnType("int");

                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CollectionId", "CardId");

                    b.HasIndex("CardId");

                    b.ToTable("CollectionCards");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Traits");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.Rarity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rarities");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.SpecialRarity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SpecialRarity");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.Card", b =>
                {
                    b.HasOne("OnePieceTcg.Domain.Models.CardSet", "CardSet")
                        .WithMany("Cards")
                        .HasForeignKey("CardSetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnePieceTcg.Domain.Models.CardType", "CardType")
                        .WithMany("Cards")
                        .HasForeignKey("CardTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnePieceTcg.Domain.Models.Color", "Color")
                        .WithMany("Cards")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnePieceTcg.Domain.Models.Rarity", "Rarity")
                        .WithMany("Cards")
                        .HasForeignKey("RarityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnePieceTcg.Domain.Models.SpecialRarity", "SpecialRarity")
                        .WithMany("Cards")
                        .HasForeignKey("SpecialRarityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OnePieceTcg.Domain.Models.User", "User")
                        .WithMany("cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardSet");

                    b.Navigation("CardType");

                    b.Navigation("Color");

                    b.Navigation("Rarity");

                    b.Navigation("SpecialRarity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.CardLine", b =>
                {
                    b.HasOne("OnePieceTcg.Domain.Models.Card", "Card")
                        .WithMany("CardLines")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnePieceTcg.Domain.Models.Line", "Line")
                        .WithMany("CardLines")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Line");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.Collection", b =>
                {
                    b.HasOne("OnePieceTcg.Domain.Models.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.CollectionCard", b =>
                {
                    b.HasOne("OnePieceTcg.Domain.Models.Card", "Card")
                        .WithMany("CollectionCards")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnePieceTcg.Domain.Models.Collection", "Collection")
                        .WithMany("CollectionCards")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.Card", b =>
                {
                    b.Navigation("CardLines");

                    b.Navigation("CollectionCards");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.CardSet", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.CardType", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.Collection", b =>
                {
                    b.Navigation("CollectionCards");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.Color", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.Line", b =>
                {
                    b.Navigation("CardLines");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.Rarity", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.SpecialRarity", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("OnePieceTcg.Domain.Models.User", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("cards");
                });
#pragma warning restore 612, 618
        }
    }
}
